baseURL = "https://web.lxdb.de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
disableLanguages = []
disqusShortname = "lxdb"
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "LXDB Team"
[Languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2019-2021 [LXDB Team](https://web.lxdb.de)"
home = "Startseite"
languageCode = "de-de"
languageName = "De"
weight = 1
[[Languages.de.menu.main]]
URL = "about"
name = "Über uns"
weight = 2
[[Languages.de.menu.main]]
URL = "feature"
name = "Initiative"
weight = 3
[[Languages.de.menu.main]]
URL = "services"
name = "Services"
weight = 4
[[Languages.de.menu.main]]
URL = "portfolio"
name = "Programme"
weight = 5
[[Languages.de.menu.main]]
URL = "team"
name = "Team"
weight = 6
[[Languages.de.menu.main]]
URL = "blog"
name = "Blog"
weight = 7
[[Languages.de.menu.main]]
URL = "contact"
name = "Kontakt"
weight = 8
[Languages.en]
contentDir = "content/english"
copyright = "copyright &copy; 2019-2020 [LXDB Team](https://web.lxdb.de)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[Languages.en.menu.main]]
URL = "feature"
name = "Initiative"
weight = 2
[[Languages.en.menu.main]]
URL = "services"
name = "Services"
weight = 3
[[Languages.en.menu.main]]
URL = "portfolio"
name = "Programs"
weight = 4
[[Languages.en.menu.main]]
URL = "team"
name = "Team"
weight = 5
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "LXDB Team"
description = "LXDB - Free software for free future."
google_analitycs_id = ""
logo = "images/logo.png"
post_share = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://code.cdn.mozilla.net/fonts/fira.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[params.preloader]
enable = true
preloader = "images/preloader.png"
[[params.social]]
icon = "ti-github"
link = "https://github.com/lxdb-team"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/lxdb_official"
[[params.social]]
icon = "ti-youtube"
link = "http://youtube.lxdb.de"
[[params.social]]
icon = "ti-instagram"
link = "https://instagram.com/lxdb_official"
[[params.social]]
icon = "ti-reddit"
link = "https://www.reddit.com/user/lxdb_official/"
